services:
  keycloak:
    image: keycloak-deploy
    container_name: keycloak-0
    depends_on:
      - keycloak-db
    environment:
      - KC_DB=mariadb
      # - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak?sslmode=disable
      # - KC_DB_USERNAME=postgres
      - KC_DB_URL=jdbc:mariadb://keycloak-db:3306/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=nzT02mptLeUpjLD9AHoPU81jO
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_URL=https://localhost:8443
      # - KC_HOSTNAME_STRICT=false
      # - KC_HTTPS_CERTIFICATE_FILE=""
      # - KC_HTTPS_CERTIFICATE_KEY_FILE=""
      - KC_PORXY_HEADERS=xforwarded
      # - KC_HOSTNAME_ADMIN=https://localhost
      # - KC_HTTPS_PORT=443
      - KC_LOG_LEVEL=INFO
    ports:
      - "8443:8443"
    restart: always
    volumes:
      - /opt/keycloak/themes:/opt/keycloak/themes

  keycloak-db:
    image: mariadb
    container_name: keycloak-db-0
    environment:
      - MARIADB_USER=keycloak
      - MARIADB_PASSWORD=nzT02mptLeUpjLD9AHoPU81jO
      - MARIADB_DATABASE=keycloak
      - MARIADB_ROOT_PASSWORD=nzT02mptLeUpjLD9AHoPU81jO
    volumes:
      - /var/lib/keycloak/myslq:/var/lib/mysql
    restart: always
  # keycloak-db:
  #   image: postgres:17
  #   container_name: keycloak-db-0
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: nzT02mptLeUpjLD9AHoPU81jO
  #     POSTGRES_DB: keycloak
  #   volumes:
  #     - /var/lib/pgsql/keycloak/data:/var/lib/postgresql/data
  #   restart: always
  #   command: ["postgres", "-c", "fsync=off"]
