services:
  keycloak:
    image: keycloak-deploy
    ports:
      - "8080:80"
    depends_on:
      - keycloak-db
    environment:
      - KC_DB=keycloak
      - KC_DB_URL=jdbc:postgres://keycloak-db:5432/keycloak?sslmode=disable
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=nzT02mptLeUpjLD9AHoPU81jO
      - KC_HOSTNAME=localhost
    volumes:
      - ./ui:/app/ui
    restart: always
  keycloak-db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nzT02mptLeUpjLD9AHoPU81jO
      POSTGRES_DB: keycloak
    ports: 
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - /etc/passwd:/etc/passwd:ro
    restart: always
      # - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: ["postgres", "-c", "fsync=off"]
